services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=server
      - POSTGRES_DB=postgres
    networks:
      - app-network
    volumes:
      - learner-vol:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=server
      - DB_NAME=postgres
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:

volumes:
  learner-vol:
